//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: common_game_res.proto
namespace Common
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GameRes")]
  public partial class GameRes : global::ProtoBuf.IExtensible
  {
    public GameRes() {}
    

    private Common.GameResType? _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public Common.GameResType type
    {
      get { return _type?? Common.GameResType.GAME_RES_TYPE_INVALID; }
      set { _type = value; }
    }
    //Here has been replaced by XXMMLLDeleter
    [global::System.ComponentModel.Browsable(false)]
    public bool typeSpecified
    {
      get { return _type != null; }
      set { if (value == (_type== null)) _type = value ? type : (Common.GameResType?)null; }
    }
    private bool ShouldSerializetype() { return typeSpecified; }
    private void Resettype() { typeSpecified = false; }
    
    private readonly global::System.Collections.Generic.List<long> _param_list = new global::System.Collections.Generic.List<long>();
    [global::ProtoBuf.ProtoMember(2, Name=@"param_list", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public global::System.Collections.Generic.List<long> param_list
    {
      get { return _param_list; }
    }
  

    private long? _expire_time;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"expire_time", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public long expire_time
    {
      get { return _expire_time?? default(long); }
      set { _expire_time = value; }
    }
    //Here has been replaced by XXMMLLDeleter
    [global::System.ComponentModel.Browsable(false)]
    public bool expire_timeSpecified
    {
      get { return _expire_time != null; }
      set { if (value == (_expire_time== null)) _expire_time = value ? expire_time : (long?)null; }
    }
    private bool ShouldSerializeexpire_time() { return expire_timeSpecified; }
    private void Resetexpire_time() { expire_timeSpecified = false; }
    

    private byte[] _data;
    [global::ProtoBuf.ProtoMember(101, IsRequired = false, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] data
    {
      get { return _data?? null; }
      set { _data = value; }
    }
    //Here has been replaced by XXMMLLDeleter
    [global::System.ComponentModel.Browsable(false)]
    public bool dataSpecified
    {
      get { return _data != null; }
      set { if (value == (_data== null)) _data = value ? data : (byte[])null; }
    }
    private bool ShouldSerializedata() { return dataSpecified; }
    private void Resetdata() { dataSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GameResWithProb")]
  public partial class GameResWithProb : global::ProtoBuf.IExtensible
  {
    public GameResWithProb() {}
    

    private int? _prob;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"prob", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int prob
    {
      get { return _prob?? default(int); }
      set { _prob = value; }
    }
    //Here has been replaced by XXMMLLDeleter
    [global::System.ComponentModel.Browsable(false)]
    public bool probSpecified
    {
      get { return _prob != null; }
      set { if (value == (_prob== null)) _prob = value ? prob : (int?)null; }
    }
    private bool ShouldSerializeprob() { return probSpecified; }
    private void Resetprob() { probSpecified = false; }
    

    private Common.GameResType? _type;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public Common.GameResType type
    {
      get { return _type?? Common.GameResType.GAME_RES_TYPE_INVALID; }
      set { _type = value; }
    }
    //Here has been replaced by XXMMLLDeleter
    [global::System.ComponentModel.Browsable(false)]
    public bool typeSpecified
    {
      get { return _type != null; }
      set { if (value == (_type== null)) _type = value ? type : (Common.GameResType?)null; }
    }
    private bool ShouldSerializetype() { return typeSpecified; }
    private void Resettype() { typeSpecified = false; }
    
    private readonly global::System.Collections.Generic.List<long> _param_list = new global::System.Collections.Generic.List<long>();
    [global::ProtoBuf.ProtoMember(3, Name=@"param_list", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public global::System.Collections.Generic.List<long> param_list
    {
      get { return _param_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"GameResSource")]
    public enum GameResSource
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_UNSPICIFIED", Value=0)]
      GAME_RES_SOURCE_UNSPICIFIED = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_MISSION", Value=1)]
      GAME_RES_SOURCE_MISSION = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_INSTANCE", Value=2)]
      GAME_RES_SOURCE_INSTANCE = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_PORTAL", Value=3)]
      GAME_RES_SOURCE_PORTAL = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_GM_COMMAND", Value=5)]
      GAME_RES_SOURCE_GM_COMMAND = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_UPGRADE_EQUIP", Value=7)]
      GAME_RES_SOURCE_UPGRADE_EQUIP = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_ADVANCED_EQUIP", Value=8)]
      GAME_RES_SOURCE_ADVANCED_EQUIP = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_INLAY_GEM", Value=9)]
      GAME_RES_SOURCE_INLAY_GEM = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_UPGRADE_GEM", Value=10)]
      GAME_RES_SOURCE_UPGRADE_GEM = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_ADVANCED_SKILL", Value=11)]
      GAME_RES_SOURCE_ADVANCED_SKILL = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_UNLOCK_HERO", Value=12)]
      GAME_RES_SOURCE_UNLOCK_HERO = 12,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_ARENA", Value=15)]
      GAME_RES_SOURCE_ARENA = 15,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_ARENA_CLEAR_CD", Value=16)]
      GAME_RES_SOURCE_ARENA_CLEAR_CD = 16,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_WORLD_BOSS", Value=20)]
      GAME_RES_SOURCE_WORLD_BOSS = 20,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_COLLECTION", Value=29)]
      GAME_RES_SOURCE_COLLECTION = 29,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_COLLECTION_SHOP", Value=30)]
      GAME_RES_SOURCE_COLLECTION_SHOP = 30,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_TERRITORY", Value=31)]
      GAME_RES_SOURCE_TERRITORY = 31,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_USE_ITEM", Value=32)]
      GAME_RES_SOURCE_USE_ITEM = 32,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_ACTIVITY_AWARD", Value=33)]
      GAME_RES_SOURCE_ACTIVITY_AWARD = 33,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_MOMO_AWARD", Value=34)]
      GAME_RES_SOURCE_MOMO_AWARD = 34,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_UPGRADE_SKILL", Value=35)]
      GAME_RES_SOURCE_UPGRADE_SKILL = 35,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_UPDATE_SKILL_POINT", Value=36)]
      GAME_RES_SOURCE_UPDATE_SKILL_POINT = 36,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_BUY_SP", Value=37)]
      GAME_RES_SOURCE_BUY_SP = 37,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_DAILY_MISSION_AWARD", Value=38)]
      GAME_RES_SOURCE_DAILY_MISSION_AWARD = 38,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_SELL_ITEM", Value=39)]
      GAME_RES_SOURCE_SELL_ITEM = 39,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_DAILY_AWARD", Value=40)]
      GAME_RES_SOURCE_DAILY_AWARD = 40,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_ONLINE_AWARD", Value=41)]
      GAME_RES_SOURCE_ONLINE_AWARD = 41,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_MOCK_EXAM_AWARD", Value=42)]
      GAME_RES_SOURCE_MOCK_EXAM_AWARD = 42,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_EXAM_RANK_AWARD", Value=43)]
      GAME_RES_SOURCE_EXAM_RANK_AWARD = 43,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_RECHARGE_AWARD", Value=44)]
      GAME_RES_SOURCE_RECHARGE_AWARD = 44,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_SANDBAGSWAR_AWARD", Value=45)]
      GAME_RES_SOURCE_SANDBAGSWAR_AWARD = 45,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_ROB_AWARD", Value=46)]
      GAME_RES_SOURCE_ROB_AWARD = 46,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_REFRESH_CHALL_HISTORY", Value=47)]
      GAME_RES_SOURCE_REFRESH_CHALL_HISTORY = 47,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_NATURE_INC_SP", Value=48)]
      GAME_RES_SOURCE_NATURE_INC_SP = 48,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_EXCHANGE_ITEM", Value=49)]
      GAME_RES_SOURCE_EXCHANGE_ITEM = 49,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_PRINTING_PRESS", Value=50)]
      GAME_RES_SOURCE_PRINTING_PRESS = 50,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_CLEAR_TRANSFORM_CD", Value=51)]
      GAME_RES_SOURCE_CLEAR_TRANSFORM_CD = 51,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_CLIMB_TOWER_AWARD", Value=52)]
      GAME_RES_SOURCE_CLIMB_TOWER_AWARD = 52,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_HERO_CELL", Value=53)]
      GAME_RES_SOURCE_HERO_CELL = 53,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_BUY_CLIMB_TOWER_COUNT", Value=54)]
      GAME_RES_SOURCE_BUY_CLIMB_TOWER_COUNT = 54,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_MSG_AWARD", Value=55)]
      GAME_RES_SOURCE_MSG_AWARD = 55,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_REVIVE_IN_INSTANCE", Value=56)]
      GAME_RES_SOURCE_REVIVE_IN_INSTANCE = 56,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_ADVANCED_HERO", Value=57)]
      GAME_RES_SOURCE_ADVANCED_HERO = 57,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_LOTTERY", Value=58)]
      GAME_RES_SOURCE_LOTTERY = 58,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_LOTTERY_SHOP", Value=59)]
      GAME_RES_SOURCE_LOTTERY_SHOP = 59,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_REVIVE_PVP_HERO", Value=60)]
      GAME_RES_SOURCE_REVIVE_PVP_HERO = 60,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_RESET_EXTRA_SP", Value=61)]
      GAME_RES_SOURCE_RESET_EXTRA_SP = 61,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_DEGREE_DEVOUR", Value=62)]
      GAME_RES_SOURCE_DEGREE_DEVOUR = 62,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_TERR_ROB", Value=63)]
      GAME_RES_SOURCE_TERR_ROB = 63,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_LEV_AWARD", Value=64)]
      GAME_RES_SOURCE_LEV_AWARD = 64,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_DEGREE_ALL_DEVOUR", Value=65)]
      GAME_RES_SOURCE_DEGREE_ALL_DEVOUR = 65,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_SIGN_AWARD", Value=66)]
      GAME_RES_SOURCE_SIGN_AWARD = 66,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_GYM_LEASE", Value=67)]
      GAME_RES_SOURCE_GYM_LEASE = 67,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_GROUP_BUILD", Value=68)]
      GAME_RES_SOURCE_GROUP_BUILD = 68,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_CREATE_GROUP", Value=69)]
      GAME_RES_SOURCE_CREATE_GROUP = 69,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_FIRE_GROUP_CAPTAIN", Value=70)]
      GAME_RES_SOURCE_FIRE_GROUP_CAPTAIN = 70,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_GROUP_OUTPUT", Value=71)]
      GAME_RES_SOURCE_GROUP_OUTPUT = 71,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_STREET_WAR", Value=72)]
      GAME_RES_SOURCE_STREET_WAR = 72,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_GVG_AWARD", Value=73)]
      GAME_RES_SOURCE_GVG_AWARD = 73,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_GROUP_SCORE_AWARD", Value=74)]
      GAME_RES_SOURCE_GROUP_SCORE_AWARD = 74,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_BUY_SKILL_POINT", Value=75)]
      GAME_RES_SOURCE_BUY_SKILL_POINT = 75,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_BUY_D_NORMAL_GIFTBAG", Value=76)]
      GAME_RES_SOURCE_BUY_D_NORMAL_GIFTBAG = 76,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_BUY_D_VIP_GIFTBAG", Value=77)]
      GAME_RES_SOURCE_BUY_D_VIP_GIFTBAG = 77,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_BUY_STREET_WAR_CHALLENGE", Value=78)]
      GAME_RES_SOURCE_BUY_STREET_WAR_CHALLENGE = 78,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_STAR_AWARD", Value=79)]
      GAME_RES_SOURCE_STAR_AWARD = 79,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_LOTTERY_DRAGON", Value=80)]
      GAME_RES_SOURCE_LOTTERY_DRAGON = 80,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_COLLECT_CLOTHES", Value=81)]
      GAME_RES_SOURCE_COLLECT_CLOTHES = 81,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_PUT_ON_CLOTHES", Value=82)]
      GAME_RES_SOURCE_PUT_ON_CLOTHES = 82,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_LOTTERY_SCHOOL", Value=83)]
      GAME_RES_SOURCE_LOTTERY_SCHOOL = 83,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_SUPPLEMENT_SIGN", Value=84)]
      GAME_RES_SOURCE_SUPPLEMENT_SIGN = 84,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_ACTIVE_HERO_COMNINATION", Value=85)]
      GAME_RES_SOURCE_ACTIVE_HERO_COMNINATION = 85,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_UNLOCK_FELLOW_CELL", Value=86)]
      GAME_RES_SOURCE_UNLOCK_FELLOW_CELL = 86,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_ARENA_SHOP", Value=87)]
      GAME_RES_SOURCE_ARENA_SHOP = 87,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_FIRST_RECHARGE_AWARD", Value=88)]
      GAME_RES_SOURCE_FIRST_RECHARGE_AWARD = 88,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_STREET_SHOP", Value=89)]
      GAME_RES_SOURCE_STREET_SHOP = 89,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_DEGREE_SHOP", Value=90)]
      GAME_RES_SOURCE_DEGREE_SHOP = 90,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_BUY_GOLD_INVEST", Value=91)]
      GAME_RES_SOURCE_BUY_GOLD_INVEST = 91,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_AWARD_GOLD_INVEST", Value=92)]
      GAME_RES_SOURCE_AWARD_GOLD_INVEST = 92,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_OPERATION", Value=93)]
      GAME_RES_SOURCE_OPERATION = 93,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_TRANSFER_HERO_EXP", Value=94)]
      GAME_RES_SOURCE_TRANSFER_HERO_EXP = 94,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_WEEK_LOGIN_AWARD", Value=95)]
      GAME_RES_SOURCE_WEEK_LOGIN_AWARD = 95,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_WEEK_RECHARGE_AWARD", Value=96)]
      GAME_RES_SOURCE_WEEK_RECHARGE_AWARD = 96,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_WEEK_RUSH_PURCHASE", Value=97)]
      GAME_RES_SOURCE_WEEK_RUSH_PURCHASE = 97,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_FC_RACE", Value=98)]
      GAME_RES_SOURCE_FC_RACE = 98,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_TEAM_PVE", Value=99)]
      GAME_RES_SOURCE_TEAM_PVE = 99,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_PASS_RACE", Value=100)]
      GAME_RES_SOURCE_PASS_RACE = 100,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_RECHARGE", Value=101)]
      GAME_RES_SOURCE_RECHARGE = 101,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_DEGREE_DECOMPOSITION", Value=120)]
      GAME_RES_SOURCE_DEGREE_DECOMPOSITION = 120,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_RECRUIT_PAOJIE", Value=121)]
      GAME_RES_SOURCE_RECRUIT_PAOJIE = 121,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_COLLECT_HERO", Value=122)]
      GAME_RES_SOURCE_COLLECT_HERO = 122,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_ADVANCED_CHUNLI", Value=123)]
      GAME_RES_SOURCE_ADVANCED_CHUNLI = 123,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_COLLECT_GEM", Value=124)]
      GAME_RES_SOURCE_COLLECT_GEM = 124,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_COLLECT_DEGREE", Value=125)]
      GAME_RES_SOURCE_COLLECT_DEGREE = 125,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_PURPLE_AWARD", Value=126)]
      GAME_RES_SOURCE_PURPLE_AWARD = 126,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_FC_RANK_AWARD", Value=127)]
      GAME_RES_SOURCE_FC_RANK_AWARD = 127,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_LEV_RANK_AWARD", Value=128)]
      GAME_RES_SOURCE_LEV_RANK_AWARD = 128,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_ARENA_RANK_AWARD", Value=129)]
      GAME_RES_SOURCE_ARENA_RANK_AWARD = 129,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_REFINE_MAGIC", Value=130)]
      GAME_RES_SOURCE_REFINE_MAGIC = 130,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_FINISH_REFINE_MAGIC", Value=131)]
      GAME_RES_SOURCE_FINISH_REFINE_MAGIC = 131,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_AWARD_REFINE_MAGIC", Value=132)]
      GAME_RES_SOURCE_AWARD_REFINE_MAGIC = 132,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_ARTIFACT_EXCHANGE", Value=135)]
      GAME_RES_SOURCE_ARTIFACT_EXCHANGE = 135,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_PUT_ON_ARTIFACT", Value=136)]
      GAME_RES_SOURCE_PUT_ON_ARTIFACT = 136,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_UPGRADE_ARTIFACT", Value=137)]
      GAME_RES_SOURCE_UPGRADE_ARTIFACT = 137,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_ADVANCE_ARTIFACT", Value=138)]
      GAME_RES_SOURCE_ADVANCE_ARTIFACT = 138,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_INLAY_ARTIFACT", Value=139)]
      GAME_RES_SOURCE_INLAY_ARTIFACT = 139,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_UPGRADE_GEM_ARTIFACT", Value=140)]
      GAME_RES_SOURCE_UPGRADE_GEM_ARTIFACT = 140,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_GEM_EXCHANGE", Value=141)]
      GAME_RES_SOURCE_GEM_EXCHANGE = 141,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_EQUIP_STARUP", Value=142)]
      GAME_RES_SOURCE_EQUIP_STARUP = 142,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_ACTIVE_TITLE", Value=143)]
      GAME_RES_SOURCE_ACTIVE_TITLE = 143,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_INNER_ACVITITY", Value=144)]
      GAME_RES_SOURCE_INNER_ACVITITY = 144,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_TOURNAMENT", Value=145)]
      GAME_RES_SOURCE_TOURNAMENT = 145,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_TOURNAMENT_SHOP", Value=146)]
      GAME_RES_SOURCE_TOURNAMENT_SHOP = 146,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_ARTIFACT_DECOMPOSE", Value=147)]
      GAME_RES_SOURCE_ARTIFACT_DECOMPOSE = 147,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_BUY_LEV_SHOP_GOODS", Value=148)]
      GAME_RES_SOURCE_BUY_LEV_SHOP_GOODS = 148,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_BUY_ITEM", Value=149)]
      GAME_RES_SOURCE_BUY_ITEM = 149,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_GROWUP", Value=150)]
      GAME_RES_SOURCE_GROWUP = 150,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_TURNTABLE", Value=151)]
      GAME_RES_SOURCE_TURNTABLE = 151,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_RESET_TURNTABLE", Value=152)]
      GAME_RES_SOURCE_RESET_TURNTABLE = 152,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_PET_FEED", Value=153)]
      GAME_RES_SOURCE_PET_FEED = 153,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_VIP_DAILY_AWARD", Value=154)]
      GAME_RES_SOURCE_VIP_DAILY_AWARD = 154,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_SEASON_AWARD", Value=155)]
      GAME_RES_SOURCE_SEASON_AWARD = 155,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_COST_GOLD", Value=156)]
      GAME_RES_SOURCE_COST_GOLD = 156,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_DAILY_SCORE_AWARD", Value=157)]
      GAME_RES_SOURCE_DAILY_SCORE_AWARD = 157,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_PET_HATCH", Value=158)]
      GAME_RES_SOURCE_PET_HATCH = 158,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_PET_LEVUP", Value=159)]
      GAME_RES_SOURCE_PET_LEVUP = 159,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_PET_ADVANCE", Value=160)]
      GAME_RES_SOURCE_PET_ADVANCE = 160,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_PET_MISSION", Value=161)]
      GAME_RES_SOURCE_PET_MISSION = 161,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_FULL_AWARD", Value=162)]
      GAME_RES_SOURCE_FULL_AWARD = 162,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_MEAT_BUN", Value=163)]
      GAME_RES_SOURCE_MEAT_BUN = 163,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_ITEM_COMPOSITE", Value=164)]
      GAME_RES_SOURCE_ITEM_COMPOSITE = 164,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_VIP_WEEK_AWARD", Value=165)]
      GAME_RES_SOURCE_VIP_WEEK_AWARD = 165,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_LIMITED_CHALLENGE", Value=166)]
      GAME_RES_SOURCE_LIMITED_CHALLENGE = 166,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_RESET_HERO_EXP", Value=167)]
      GAME_RES_SOURCE_RESET_HERO_EXP = 167,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_LIMITED_MISSION", Value=168)]
      GAME_RES_SOURCE_LIMITED_MISSION = 168,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_ADVANCED_DEGREE", Value=169)]
      GAME_RES_SOURCE_ADVANCED_DEGREE = 169,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_EGG_LOTTERY_RANK_AWARD", Value=170)]
      GAME_RES_SOURCE_EGG_LOTTERY_RANK_AWARD = 170,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_ITEM_EXPIRE", Value=171)]
      GAME_RES_SOURCE_ITEM_EXPIRE = 171,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_BUY_RUNNING_RACE_COUNT", Value=172)]
      GAME_RES_SOURCE_BUY_RUNNING_RACE_COUNT = 172,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_SINGLE_RUNNING_RACE", Value=173)]
      GAME_RES_SOURCE_SINGLE_RUNNING_RACE = 173,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_RANK_RUNNING_RACE", Value=174)]
      GAME_RES_SOURCE_RANK_RUNNING_RACE = 174,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_PRACTICE_EXCHANGE", Value=175)]
      GAME_RES_SOURCE_PRACTICE_EXCHANGE = 175,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_PRACTICE", Value=176)]
      GAME_RES_SOURCE_PRACTICE = 176,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_REVERT_PRACTICE", Value=177)]
      GAME_RES_SOURCE_REVERT_PRACTICE = 177,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_REVERT_HERO_START", Value=178)]
      GAME_RES_SOURCE_REVERT_HERO_START = 178,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_SOURCE_BUY_GROUP_SP_WELFARE", Value=179)]
      GAME_RES_SOURCE_BUY_GROUP_SP_WELFARE = 179
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"GameResType")]
    public enum GameResType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_TYPE_INVALID", Value=0)]
      GAME_RES_TYPE_INVALID = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_TYPE_COIN", Value=1)]
      GAME_RES_TYPE_COIN = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_TYPE_GOLD", Value=2)]
      GAME_RES_TYPE_GOLD = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_TYPE_EXP", Value=3)]
      GAME_RES_TYPE_EXP = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_TYPE_ITEM", Value=4)]
      GAME_RES_TYPE_ITEM = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_TYPE_FAME", Value=5)]
      GAME_RES_TYPE_FAME = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_TYPE_SP", Value=6)]
      GAME_RES_TYPE_SP = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_TYPE_VIP_EXP", Value=7)]
      GAME_RES_TYPE_VIP_EXP = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_TYPE_SKILL_POINT", Value=8)]
      GAME_RES_TYPE_SKILL_POINT = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_TYPE_SCORE", Value=9)]
      GAME_RES_TYPE_SCORE = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_TYPE_HERO", Value=10)]
      GAME_RES_TYPE_HERO = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_TYPE_PET", Value=11)]
      GAME_RES_TYPE_PET = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GAME_RES_TYPE_MAX", Value=12)]
      GAME_RES_TYPE_MAX = 12
    }
  
}