//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: common_activity.proto
namespace Common
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ActivityMission")]
  public partial class ActivityMission : global::ProtoBuf.IExtensible
  {
    public ActivityMission() {}
    

    private Common.ActivityType? _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public Common.ActivityType type
    {
      get { return _type?? Common.ActivityType.ACTIVITY_TYPE_INVALID; }
      set { _type = value; }
    }
    //Here has been replaced by XXMMLLDeleter
    [global::System.ComponentModel.Browsable(false)]
    public bool typeSpecified
    {
      get { return _type != null; }
      set { if (value == (_type== null)) _type = value ? type : (Common.ActivityType?)null; }
    }
    private bool ShouldSerializetype() { return typeSpecified; }
    private void Resettype() { typeSpecified = false; }
    

    private Common.ActivityMission.State? _state;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"state", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public Common.ActivityMission.State state
    {
      get { return _state?? Common.ActivityMission.State.STATE_UNFINISHED; }
      set { _state = value; }
    }
    //Here has been replaced by XXMMLLDeleter
    [global::System.ComponentModel.Browsable(false)]
    public bool stateSpecified
    {
      get { return _state != null; }
      set { if (value == (_state== null)) _state = value ? state : (Common.ActivityMission.State?)null; }
    }
    private bool ShouldSerializestate() { return stateSpecified; }
    private void Resetstate() { stateSpecified = false; }
    

    private int? _finish_cond;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"finish_cond", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int finish_cond
    {
      get { return _finish_cond?? default(int); }
      set { _finish_cond = value; }
    }
    //Here has been replaced by XXMMLLDeleter
    [global::System.ComponentModel.Browsable(false)]
    public bool finish_condSpecified
    {
      get { return _finish_cond != null; }
      set { if (value == (_finish_cond== null)) _finish_cond = value ? finish_cond : (int?)null; }
    }
    private bool ShouldSerializefinish_cond() { return finish_condSpecified; }
    private void Resetfinish_cond() { finish_condSpecified = false; }
    

    private int? _progress;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"progress", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int progress
    {
      get { return _progress?? default(int); }
      set { _progress = value; }
    }
    //Here has been replaced by XXMMLLDeleter
    [global::System.ComponentModel.Browsable(false)]
    public bool progressSpecified
    {
      get { return _progress != null; }
      set { if (value == (_progress== null)) _progress = value ? progress : (int?)null; }
    }
    private bool ShouldSerializeprogress() { return progressSpecified; }
    private void Resetprogress() { progressSpecified = false; }
    

    private int? _score_addition;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"score_addition", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int score_addition
    {
      get { return _score_addition?? default(int); }
      set { _score_addition = value; }
    }
    //Here has been replaced by XXMMLLDeleter
    [global::System.ComponentModel.Browsable(false)]
    public bool score_additionSpecified
    {
      get { return _score_addition != null; }
      set { if (value == (_score_addition== null)) _score_addition = value ? score_addition : (int?)null; }
    }
    private bool ShouldSerializescore_addition() { return score_additionSpecified; }
    private void Resetscore_addition() { score_additionSpecified = false; }
    
    [global::ProtoBuf.ProtoContract(Name=@"State")]
    public enum State
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"STATE_UNFINISHED", Value=0)]
      STATE_UNFINISHED = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"STATE_FINISHED", Value=1)]
      STATE_FINISHED = 1
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ActivityAwardStatus")]
  public partial class ActivityAwardStatus : global::ProtoBuf.IExtensible
  {
    public ActivityAwardStatus() {}
    

    private int? _score;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int score
    {
      get { return _score?? default(int); }
      set { _score = value; }
    }
    //Here has been replaced by XXMMLLDeleter
    [global::System.ComponentModel.Browsable(false)]
    public bool scoreSpecified
    {
      get { return _score != null; }
      set { if (value == (_score== null)) _score = value ? score : (int?)null; }
    }
    private bool ShouldSerializescore() { return scoreSpecified; }
    private void Resetscore() { scoreSpecified = false; }
    

    private bool? _awarded;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"awarded", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool awarded
    {
      get { return _awarded?? default(bool); }
      set { _awarded = value; }
    }
    //Here has been replaced by XXMMLLDeleter
    [global::System.ComponentModel.Browsable(false)]
    public bool awardedSpecified
    {
      get { return _awarded != null; }
      set { if (value == (_awarded== null)) _awarded = value ? awarded : (bool?)null; }
    }
    private bool ShouldSerializeawarded() { return awardedSpecified; }
    private void Resetawarded() { awardedSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Activity")]
  public partial class Activity : global::ProtoBuf.IExtensible
  {
    public Activity() {}
    
    private readonly global::System.Collections.Generic.List<Common.ActivityMission> _activity_list = new global::System.Collections.Generic.List<Common.ActivityMission>();
    [global::ProtoBuf.ProtoMember(1, Name=@"activity_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Common.ActivityMission> activity_list
    {
      get { return _activity_list; }
    }
  
    private readonly global::System.Collections.Generic.List<Common.ActivityAwardStatus> _award_list = new global::System.Collections.Generic.List<Common.ActivityAwardStatus>();
    [global::ProtoBuf.ProtoMember(2, Name=@"award_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Common.ActivityAwardStatus> award_list
    {
      get { return _award_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"ActivityType")]
    public enum ActivityType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ACTIVITY_TYPE_INVALID", Value=0)]
      ACTIVITY_TYPE_INVALID = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ACTIVITY_TYPE_ELITE_CHALLENGE", Value=1)]
      ACTIVITY_TYPE_ELITE_CHALLENGE = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ACTIVITY_TYPE_DEVIL_CHALLENGE", Value=2)]
      ACTIVITY_TYPE_DEVIL_CHALLENGE = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ACTIVITY_TYPE_ARENA_CHALLENGE", Value=3)]
      ACTIVITY_TYPE_ARENA_CHALLENGE = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ACTIVITY_TYPE_TERRITORY_BONUS", Value=4)]
      ACTIVITY_TYPE_TERRITORY_BONUS = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ACTIVITY_TYPE_UPGRADE_EQUIP", Value=5)]
      ACTIVITY_TYPE_UPGRADE_EQUIP = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ACTIVITY_TYPE_COMPLETE_DM", Value=6)]
      ACTIVITY_TYPE_COMPLETE_DM = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ACTIVITY_TYPE_BUY_SP", Value=7)]
      ACTIVITY_TYPE_BUY_SP = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ACTIVITY_TYPE_MOMO_FRIENDS", Value=8)]
      ACTIVITY_TYPE_MOMO_FRIENDS = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ACTIVITY_TYPE_SANDBAGS_WARS", Value=9)]
      ACTIVITY_TYPE_SANDBAGS_WARS = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ACTIVITY_TYPE_MOCK_EXAM", Value=10)]
      ACTIVITY_TYPE_MOCK_EXAM = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ACTIVITY_TYPE_PRINTING_PRESS", Value=11)]
      ACTIVITY_TYPE_PRINTING_PRESS = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ACTIVITY_TYPE_CLIMB_TOWER", Value=12)]
      ACTIVITY_TYPE_CLIMB_TOWER = 12,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ACTIVITY_TYPE_STREET_WAR", Value=13)]
      ACTIVITY_TYPE_STREET_WAR = 13,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ACTIVITY_TYPE_TEAM_PVE", Value=14)]
      ACTIVITY_TYPE_TEAM_PVE = 14,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ACTIVITY_TYPE_TOURNAMENT", Value=15)]
      ACTIVITY_TYPE_TOURNAMENT = 15,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ACTIVITY_TYPE_TURNTABLE", Value=16)]
      ACTIVITY_TYPE_TURNTABLE = 16,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ACTIVITY_TYPE_LOTTERY", Value=17)]
      ACTIVITY_TYPE_LOTTERY = 17,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ACTIVITY_TYPE_END", Value=18)]
      ACTIVITY_TYPE_END = 18
    }
  
}