//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: common_scene.proto
namespace Common
{
    [global::ProtoBuf.ProtoContract(Name=@"SceneType")]
    public enum SceneType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCENE_TYPE_INVALID", Value=0)]
      SCENE_TYPE_INVALID = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCENE_TYPE_MAIN", Value=1)]
      SCENE_TYPE_MAIN = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SCENE_TYPE_COPY", Value=2)]
      SCENE_TYPE_COPY = 2
    }
  
}